---
- hosts: admin
  vars_files:
    - vars/ceph_info.yml
  tasks:
    - name: Add hosts
      lineinfile: dest=/etc/hosts line="{{item.privateIp}} {{item.hostname}}"
      become: yes
      with_items: "{{mons + osds}}"
    - name: copy key # check if multiple keys to be copied for different nodes
      copy: src='{{IdentityFile_src}}' dest='{{IdentityFile}}' mode=400
    - name: Create ssh config file
      file: path=~/.ssh/config state=touch
    - name: Add ssh config entries
      lineinfile:
        dest=~/.ssh/config
        line="Host {{item.hostname}}\n Hostname {{item.hostname}}\n User {{ceph_user}}\n IdentityFile {{IdentityFile}}\n StrictHostKeyChecking no\n UserKnownHostsFile=/dev/null"
      with_items: "{{mons + osds}}"

- hosts: nodes
  vars_files:
    - vars/ceph_info.yml
  tasks:
    - name: Add hosts entry in node
      lineinfile: dest=/etc/hosts line="{{item.privateIp}} {{item.hostname}}" state=present
      become: yes
      with_items: "{{mons + osds}}"
    - include: apt_get_update.yaml
    - name: Install ntp
      apt: name=ntp state=installed force=yes
      become: yes
    - name: Install git
      apt: name=git state=installed force=yes
      become: yes
    - name: create a new user
      user: 
          name={{ceph_user}}
          createhome=yes 
          state=present
          groups="sudo"
          password={{ceph_password}}
          comment="Created user for ansible"
      become: yes
    - name: Add to sudoers
      shell: echo "{{ceph_user}} ALL = (ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/{{ceph_user}}
    - name: Set user permissions 
      shell: sudo chmod 0440 /etc/sudoers.d/{{ceph_user}}
   
    - name: Set up git
      shell: git config --global url."https://".insteadOf git://
